server:
  port: 8091
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
    gateway:
      enabled: true # default value
  security:
    enabled: false

openapi:
  service:
    title: department-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8090 #api gateway url

springdoc:
  api-docs:
    path: /departments/v3/api-docs
    enabled: false  # Disable swagger api-docs in Prod env
  swagger-ui:
    path: /departments/swagger-ui.html
    defaultModelsExpandDepth: -1
    enabled: false  # Disable swagger ui in Prod env

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

message: "PROD TESTING"

spring:
  cloud:
    bus:
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
